version: 2.1
orbs:
  architect: giantswarm/architect@2.4.2

workflows:
  version: 2
  build:
    jobs:
      - architect/push-to-app-catalog:
          name: push-to-default-app-catalog
          app_catalog: "default-catalog"
          app_catalog_test: "default-test-catalog"
          chart: "kiam-app"
          executor: "app-build-suite"
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/integration-test:
          context: architect
          name: basic-integration-test
          install-app-platform: true
          test-dir: "integration/test/basic"
          filters:
            # Do not trigger the job on merge to master.
            branches:
              ignore:
                - master
          requires:
            - push-to-default-app-catalog
