apiVersion: v1
name: kiam-app
version: [[ .Version ]]
appVersion: "4.2"
description: Integrate AWS IAM with Kubernetes
home: https://github.com/uswitch/kiam
icon: https://s.giantswarm.io/app-icons/kiam/1/dark.svg
annotations:
  application.giantswarm.io/team: "phoenix"
