{{ if .Values.namespaceAnnotator.enabled }}
{{ range .Values.namespaceAnnotator.namespaces }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ $.Values.namespaceAnnotator.name }}-{{ .name }}
  namespace: {{ $.Values.namespaceAnnotator.namespace }}
  labels:
    app: {{ $.Values.namespaceAnnotator.name }}
    giantswarm.io/service-type: "managed"
spec:
  podSelector:
    matchLabels:
      job-name: {{ $.Values.namespaceAnnotator.name }}-{{ .name }}
  ingress:
  - {}
  egress:
  - {}
  policyTypes:
  - Egress
  - Ingress
{{ end }}
{{ end }}
