{{ if and .Values.namespaceAnnotator.enabled }}
{{ if gt (len .Values.namespaceAnnotator.namespaces) 0 }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.namespaceAnnotator.name }}
  labels:
    app: {{ .Values.namespaceAnnotator.name }}
    giantswarm.io/service-type: "managed"
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  resourceNames:
  {{- range .Values.namespaceAnnotator.namespaces }}
  - {{ .name }}
  {{- end }}
  verbs:
  - "get"
  - "patch"
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ .Values.namespaceAnnotator.name }}
  verbs:
  - "use"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.namespaceAnnotator.name }}
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": "hook-succeeded,hook-failed"
  labels:
    app: {{ .Values.namespaceAnnotator.name }}
    giantswarm.io/service-type: "managed"
subjects:
  - kind: ServiceAccount
    name: {{ .Values.namespaceAnnotator.name }}
    namespace: {{ .Values.namespaceAnnotator.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.namespaceAnnotator.name }}
  apiGroup: rbac.authorization.k8s.io
{{ end }}
{{ end }}
