{{ if .Values.namespaceAnnotator.enabled }}
{{ if gt (len .Values.namespaceAnnotator.namespaces) 0 }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.namespaceAnnotator.name }}
  namespace: {{ .Values.namespaceAnnotator.namespace }}
  labels:
    app: {{ .Values.namespaceAnnotator.name }}
    giantswarm.io/service-type: "managed"
{{ end }}
{{ end }}
