apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.agent.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
    component: {{ .Values.agent.name }}
    giantswarm.io/service-type: "managed"
