apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ .Values.agent.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.agent" . | nindent 4 }}
spec:
  privileged: false
  allowPrivilegeEscalation: false
  allowedCapabilities:
    - "NET_ADMIN"
  volumes:
    - 'secret'
    - 'hostPath'
  allowedHostPaths:
    - pathPrefix: "/run/xtables.lock"
  hostNetwork: true
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false
