apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ .Values.agent.name }}-psp-use
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.agent.name }}
    giantswarm.io/service-type: "managed"
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ .Values.agent.name }}
  verbs:
  - use
