apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.agent.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.agent" . | nindent 4 }}
    giantswarm.io/monitoring: "true"
  annotations:
    {{- if .Values.agent.prometheus.scrape }}
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.agent.prometheus.port | quote }}
    {{- end }}
    giantswarm.io/monitoring-port: {{ .Values.agent.prometheus.port | quote }}
spec:
  clusterIP: None
  selector:
    {{- include "labels.selector.agent" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.agent.prometheus.port }}
      targetPort: {{ .Values.agent.prometheus.port }}
      protocol: TCP
