apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ .Values.agent.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
    component: {{ .Values.agent.name }}
    giantswarm.io/service-type: "managed"
spec:
  endpointSelector:
    matchLabels:
      {{- include "labels.selector.agent" . | nindent 6 }}
  ingress:
    - fromEntities:
        - cluster
      toPorts:
        - ports:
            - port: {{ .Values.agent.host.port }}
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: prometheus
      toPorts:
        - ports:
            - port: {{ .Values.agent.prometheus.port }}
  egress:
    - toEndpoints:
        - matchLabels:
            app: kiam
            component: kiam-server
      toPorts:
        - ports:
            - port: {{ .Values.server.service.targetPort }}
    - toServices:
        - k8sServiceSelector:
            selector:
              matchLabels:
                k8s-app: coredns
      toPorts:
        - ports:
            - port: "53"