apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.agent.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.agent.name }}
    giantswarm.io/service-type: "managed"