apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: {{ .Values.name }}-selfsigning-issuer
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Values.name }}-ca
spec:
  secretName: {{ .Values.name }}-ca-tls
  commonName: {{ .Values.name }}
  isCA: true
  issuerRef:
    name: {{ .Values.name }}-selfsigning-issuer

---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: {{ .Values.name }}-ca-issuer
spec:
  ca:
    secretName: {{ .Values.name }}-ca-tls

---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Values.agent.name }}
spec:
  secretName: {{ .Values.agent.name }}-tls
  commonName: {{ .Values.agent.name }}
  issuerRef:
    name: {{ .Values.name }}-ca-issuer

---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Values.server.name }}
spec:
  secretName: {{ .Values.server.name }}-tls
  commonName: {{ .Values.server.name }}
  issuerRef:
    name: {{ .Values.name }}-ca-issuer
  dnsNames:
  - "localhost"
  - "{{ .Values.server.name }}"
  ipAddresses:
  - "127.0.0.1"