apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.name }}-selfsigning-issuer
  labels:
    app: {{ .Values.name | quote }}
    {{- include "labels.common" . | nindent 4 }}
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.name }}-ca
  labels:
    app: {{ .Values.name | quote }}
    {{- include "labels.common" . | nindent 4 }}
spec:
  secretName: {{ .Values.name }}-ca-tls
  commonName: {{ .Values.name }}
  isCA: true
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: {{ .Values.name }}-selfsigning-issuer

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.name }}-ca-issuer
  labels:
    app: {{ .Values.name | quote }}
    {{- include "labels.common" . | nindent 4 }}
spec:
  ca:
    secretName: {{ .Values.name }}-ca-tls

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.agent.name }}
  labels:
    {{- include "labels.agent" . | nindent 4 }}
spec:
  secretName: {{ .Values.agent.name }}-tls
  commonName: {{ .Values.agent.name }}
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: {{ .Values.name }}-ca-issuer

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.server.name }}
  labels:
    {{- include "labels.server" . | nindent 4 }}
spec:
  secretName: {{ .Values.server.name }}-tls
  commonName: {{ .Values.server.name }}
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: {{ .Values.name }}-ca-issuer
  dnsNames:
  - "localhost"
  - "{{ .Values.server.name }}"
  ipAddresses:
  - "127.0.0.1"
