{{ if .Values.ciliumNetworkPolicy.enabled }}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: "{{ template "Values.name" . }}"
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      app: {{ .Values.name | quote }}
  egress:
    - toEntities:
        - kube-apiserver
        - world
{{ end }}
