apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.server.name }}-psp-use
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.server" . | nindent 4 }}
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ .Values.server.name }}
  verbs:
  - use
