kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Values.server.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.server" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "labels.selector.server" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - port: {{ .Values.server.service.targetPort }}
      protocol: TCP
  - ports:
    - port: {{ .Values.server.prometheus.port }}
      protocol: TCP
  egress:
  - {}

