apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ .Values.server.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.server" . | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      {{- include "labels.selector.server" . | nindent 6 }}
  ingress:
    - fromEndpoints:
        - matchLabels:
            app: kiam
            component: kiam-agent
      toPorts:
        - ports:
            - port: "{{ .Values.server.service.targetPort }}"
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: prometheus
      toPorts:
        - ports:
            - port: "{{ .Values.server.prometheus.port }}"
  egress:
    - toCIDRSet:
        - cidr: 169.254.169.254/32
      toPorts:
        - ports:
            - port: "80"
    - toEndpoints:
        - matchLabels:
            k8s-app: coredns
            io.kubernetes.pod.namespace: kube-system
      toPorts:
        - ports:
            - port: "53"
