apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ .Values.server.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.server" . | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      {{- include "labels.selector.server" . | nindent 6 }}
  ingress:
    - fromEntities:
        - cluster
        - world
  egress:
    - toEntities:
        - cluster
        - world
