apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.server.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.server.name }}
    giantswarm.io/service-type: "managed"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.server.name }}-psp-use
subjects:
- kind: ServiceAccount
  name: {{ template "kiam.serviceAccountName.server" . }}
  namespace: {{ .Values.namespace }}
