apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.server.name }}-read
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.server" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.server.name }}-read
subjects:
- kind: ServiceAccount
  name: {{ .Values.server.name }}
  namespace: {{ .Release.Namespace }}
