apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.server.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
    component: {{ .Values.server.name }}
    giantswarm.io/service-type: "managed"
  annotations:
    {{- if .Values.server.prometheus.scrape }}
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.server.prometheus.port | quote }}
    {{- end }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.name }}
    component: {{ .Values.server.name }}
  ports:
    {{- if .Values.server.prometheus.scrape }}
    - name: metrics
      port: {{ .Values.server.prometheus.port }}
      targetPort: {{ .Values.server.prometheus.port }}
      protocol: TCP
    {{- end }}
    - name: grpclb
      port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.targetPort }}
      protocol: TCP
