apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-delete-policy": "hook-succeeded"
  labels:
    app: {{ .Values.name }}
    giantswarm.io/service-type: "managed"
spec:
  template:
    spec:
      serviceAccountName: {{ .Values.name }}
      securityContext:
        runAsUser: {{ .Values.userID }}
        runAsGroup: {{ .Values.groupID }}
      containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.global.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        command:
        - /bin/sh
        - -c 
        - "/usr/local/bin/kubectl annotate namespace kube-system iam.amazonaws.com/permitted=.* --overwrite"
        resources:
{{ toYaml .Values.resources | indent 10 }}
      restartPolicy: OnFailure
  backoffLimit: 4
