apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ .Values.name }}
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": "hook-succeeded,hook-failed"
  labels:
    app: {{ .Values.name }}
    giantswarm.io/service-type: "managed"
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  resourceName:
  - kube-system
  verbs:
  - "get"
  - "patch"
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ .Values.name }}
  verbs:
  - "use"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ .Values.name }}
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": "hook-succeeded,hook-failed"
  labels:
    app: {{ .Values.name }}
    giantswarm.io/service-type: "managed"
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  apiGroup: rbac.authorization.k8s.io
